---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hitosea.com
  resources:
  - schedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hitosea.com
  resources:
  - schedules/finalizers
  verbs:
  - update
- apiGroups:
  - hitosea.com
  resources:
  - schedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachinerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachinerestores/finalizers
  verbs:
  - update
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachinerestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachineschedulesnapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachinesnapshotcontents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachinesnapshotcontents/finalizers
  verbs:
  - update
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachinesnapshotcontents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachinesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachinesnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachinesnapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines/status
  verbs:
  - get
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  verbs:
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents/status
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots/status
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
