# permissions for end users to view schedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: schedule-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: histore
    app.kubernetes.io/part-of: histore
    app.kubernetes.io/managed-by: kustomize
  name: schedule-viewer-role
rules:
- apiGroups:
  - hitosea.com
  resources:
  - schedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hitosea.com
  resources:
  - schedules/status
  verbs:
  - get
