# permissions for end users to edit virtualmachinesnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualmachinesnapshot-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: histore
    app.kubernetes.io/part-of: histore
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachinesnapshot-editor-role
rules:
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachinesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hitosea.com
  resources:
  - virtualmachinesnapshots/status
  verbs:
  - get
